from pydantic import BaseModel, Field

## from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from langchain_google_genai import ChatGoogleGenerativeAI

from dotenv import load_dotenv
from typing import Literal, Optional
import json

load_dotenv ()


with open('json_schema.json', 'r') as f:
    json_schema = json.load(f)


'''
HFEndPt = HuggingFaceEndpoint(
    repo_id = 'deepseek-ai/DeepSeek-V3.2-Exp',
    huggingfacehub_api_token = os.getenv('HUGGINGFACEHUB_ACCESS_TOKEN'),
    max_new_tokens = 100,
    temperature = 1.2
)
'''


model = ChatGoogleGenerativeAI(model = 'gemini-2.5-pro')


## Schema
## Defines the way in which output has been generated by the Model
class Review (BaseModel):
    key_themes: list[str] = Field(description = "Write down all the key themes mentioned in the user review")
    summary: str = Field(description = "Generate the summary of the review")
    sentiment: Literal['Positive', 'Negative'] = Field(description = 'What is the sentiment behind the user review')
    pros: Optional[list[str]] = Field(default = None, description = 'Generate the pros mentioned by the user in the review')
    cons: Optional[list[str]] = Field(default = None, description = 'Generate the pros mentioned by the user in the review')
    name: Optional[str] = Field(default = None, defadescription = 'What is the name of the reviewer')


## model = ChatHuggingFace(llm = HFEndPt)


structured_model = model.with_structured_output(json_schema)

result = structured_model.invoke ('''
    Samsung-S23 is one of the best smartphones in its segment, designed for optimal daily use. 
    The camera quality is impressive even in low light, and the sleek design makes it comfortable to hold. 
    However, the battery life is average, and the phone can get warm after extended gaming sessions. 
    Overall, I am very satisfied with the performance and features.              
''')

print (result)

